name: security_scans
on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  scan_docker_images:
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        image: ["accesspod:latest",
                "daemons:latest",
                "query-optimizer:latest",
                "server:latest",
                "static-files:latest"]
    steps:
      - uses: actions/checkout@v4.0.0
        with:
          ref: ${{ github.head_ref }}
          fetch-depth: 1

      - name: Run Trivy vulnerability scanner in fs mode
        uses: Maxim-Durand/trivy-action@master
        with:
          image-ref: "${{ vars.STAGING_DOCKER_REGISTRY }}/${{ matrix.image }}"
          scan-type: image
          format: 'github'
          output: 'dependency-results.sbom.json'
          github-pat: ${{ secrets.GITHUB_TOKEN }}
          severity: "MEDIUM,HIGH,CRITICAL"
          scanners: "vuln"
        env:
          TRIVY_USERNAME: "${{ secrets.STAGING_DOCKER_REGISTRY_ADMIN_USERNAME }}"
          TRIVY_PASSWORD: "${{ secrets.STAGING_DOCKER_REGISTRY_ADMIN_PASSWORD }}"
